baseURL = "https://fwrq41251.github.io/"
languageCode = "zh-cn"
title = "winry's" # æˆ–è€…æ‚¨å–œæ¬¢çš„ä»»ä½•æ ‡é¢˜
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"] # å…³é”®æ˜¯æ·»åŠ  "JSON"

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

# [[menu.main]]
#     identifier = "about"
#     name = "å…³äºæˆ‘"
#     url = "/about/"
#     weight = 30

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40

[params]
  defaultTheme = "auto" 
  ShowReadingTime = true      # æ˜¾ç¤ºæ–‡ç« é˜…è¯»æ—¶é—´ (æ‚¨å·²ç»å¯ç”¨äº†)
  ShowShareButtons = true     # åœ¨æ–‡ç« æœ«å°¾æ˜¾ç¤ºç¤¾äº¤åˆ†äº«æŒ‰é’®
  ShowPostNavLinks = true     # åœ¨æ–‡ç« æœ«å°¾æ˜¾ç¤ºâ€œä¸Šä¸€ç¯‡/ä¸‹ä¸€ç¯‡â€çš„å¯¼èˆªé“¾æ¥
  ShowBreadCrumbs = true      # æ˜¾ç¤ºé¢åŒ…å±‘å¯¼èˆª (ä¾‹å¦‚: Home > Posts > My Post)
  ShowCodeCopyButtons = true  # ä¸ºä»£ç å—å¯ç”¨ä¸€é”®å¤åˆ¶æŒ‰é’® (å¯¹æŠ€æœ¯åšå®¢éå¸¸æœ‰ç”¨!)
  # æ˜¯å¦é»˜è®¤å±•å¼€æ–‡ç« ç›®å½• (TOC - Table of Contents)
  # ä¹Ÿå¯ä»¥åœ¨å•ç¯‡æ–‡ç« çš„ Front Matter ä¸­ç”¨ toc: true æ¥æ§åˆ¶
  TocOpen = false

  [params.homeInfoParams]
    Title = "ğŸŒ™"
    Content = """
Things about java, vim, linux.
"""
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/fwrq41251"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/winryko"
